// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMudPieSystem {
  function claim(bytes32 name) external;

  function setAbout(bytes32 name, string memory about) external;
}
